import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Calculator,
  Users,
  HeartHandshake,
  Settings,
  Box,
  Truck,
  Layers,
  History,
  PieChart,
  FileText,
  UserPlus,
  CalendarDays,
  Hash,
  Activity,
  Key,
  BellRing,
  Percent,
  Coins,
  FileClock,
  Shield,
  Briefcase,
  MapPin,
  Store,
  GitPullRequest,
  CreditCard,
  Sliders,
  BarChart3,
  TrendingUp,
  AlertCircle,
  BookOpen,
  Receipt,
  Wallet,
  Building,
  Gavel,
  Landmark,
  ArrowRightLeft,
  ClipboardCheck,
  Scale,
  PackageSearch,
  Timer,
  Factory,
  Database,
  BrainCircuit,
  Sparkles,
  Search,
  Skull,
  AlertTriangle,
  Boxes,
  Tags,
  Barcode,
  ClipboardList,
  Quote,
  ClipboardCheck as OrderIcon,
  ArrowLeftRight,
  UserCheck,
  Users2,
  PackageCheck,
  Hourglass,
  BadgeCent,
  Navigation,
  CarFront,
  CheckCircle2,
  Route,
  Zap,
  Target,
  LineChart,
  FilePlus2,
  ListTree,
  Star,
  Gift,
  Mail,
  UserCircle,
  Globe,
  Settings2,
  Fingerprint,
  Lock,
  Clock,
  ShieldCheck,
  Globe2,
  UserCog,
  Stethoscope,
  Timer as ClockIcon,
  CalendarCheck,
  ShieldAlert,
  Flame,
  FileCheck,
  GraduationCap,
  UserSearch,
  HandCoins,
  Coins as PayrollIcon,
  Banknote,
  Cog,
  FileBadge,
  RefreshCw,
  PlayCircle,
  GanttChart,
  Building2,
  Monitor
} from "lucide-react"

export interface NavSubmenu {
  title: string
  icon: any
  url: string
  id: string 
}

export interface NavItem {
  title: string
  icon: any
  url: string
  pattern: RegExp
  id: string 
  submenus?: NavSubmenu[]
}

export const navConfig: NavItem[] = [
  { 
    title: "Command Center", 
    icon: LayoutDashboard, 
    url: "/", 
    pattern: /^\/($|dashboard)/,
    id: "dashboard"
  },
  {
    title: "Workflow Hub",
    icon: GanttChart,
    url: "/approvals",
    pattern: /^\/approvals/,
    id: "approvals",
    submenus: [
      { title: "Control Panel", icon: LayoutDashboard, url: "/approvals", id: "overview" },
      { title: "Active Queue", icon: Zap, url: "/approvals?tab=Pending", id: "pending" },
      { title: "Decision History", icon: History, url: "/approvals?tab=History", id: "history" },
      { title: "Workflow Setup", icon: Settings2, url: "/admin/approval-workflows", id: "setup" },
    ]
  },
  {
    title: "AI Strategist",
    icon: BrainCircuit,
    url: "/ai-insights",
    pattern: /^\/ai-insights/,
    id: "ai_strategist"
  },
  { 
    title: "iClick POS", 
    icon: ShoppingCart, 
    url: "/pos", 
    pattern: /^\/pos/,
    id: "pos"
  },
  {
    title: "Payroll Engine",
    icon: Banknote,
    url: "/payroll",
    pattern: /^\/payroll/,
    id: "payroll",
    submenus: [
      { title: "Dashboard", icon: LayoutDashboard, url: "/payroll", id: "overview" },
      { title: "Salary Structure", icon: Layers, url: "/payroll/structure", id: "structure" },
      { title: "Run Processing", icon: RefreshCw, url: "/payroll/processing", id: "processing" },
      { title: "Statutory Hub", icon: Landmark, url: "/payroll/statutory", id: "statutory" },
      { title: "Loans & Advances", icon: HandCoins, url: "/payroll/loans", id: "loans" },
      { title: "Payslip Vault", icon: FileBadge, url: "/payroll/payslips", id: "payslips" },
      { title: "Payroll Setup", icon: Settings2, url: "/payroll/setup", id: "setup" },
      { title: "Payroll Reports", icon: BarChart3, url: "/payroll/reports", id: "reports" },
    ]
  },
  {
    title: "Human Resource",
    icon: Users,
    url: "/hr",
    pattern: /^\/hr/,
    id: "hr",
    submenus: [
      { title: "Employee Hub", icon: UserCog, url: "/hr/employees", id: "employees" },
      { title: "Time & Attendance", icon: ClockIcon, url: "/hr/attendance", id: "attendance" },
      { title: "Recruitment (ATS)", icon: UserSearch, url: "/hr/recruitment", id: "recruitment" },
      { title: "Leave & Absence", icon: CalendarDays, url: "/hr/leave", id: "leave" },
      { title: "Training (LMS)", icon: GraduationCap, url: "/hr/training", id: "training" },
      { title: "HR Forecasting", icon: LineChart, url: "/hr/forecasting", id: "forecasting" },
      { title: "Leave Approvals", icon: FileCheck, url: "/hr/leave-approvals", id: "leave_approvals" },
      { title: "Performance", icon: Star, url: "/hr/performance", id: "performance" },
      { title: "Conduct & Discipline", icon: ShieldAlert, url: "/hr/disciplinary", id: "disciplinary" },
      { title: "HR Setup", icon: Settings2, url: "/hr/setup", id: "setup" },
    ]
  },
  {
    title: "Client Care", 
    icon: HeartHandshake, 
    url: "/crm", 
    pattern: /^\/crm/,
    id: "crm",
    submenus: [
      { title: "Client Directory", icon: Users, url: "/crm/customers", id: "customers" },
      { title: "Loyalty Hub", icon: Star, url: "/crm/loyalty", id: "loyalty" },
      { title: "Stored Value", icon: Wallet, url: "/crm/wallet", id: "wallet" },
      { title: "Marketing Cloud", icon: Mail, url: "/crm/marketing", id: "marketing" },
      { title: "Promo Manager", icon: Percent, url: "/crm/promos", id: "promos" },
      { title: "Gift Cards", icon: Gift, url: "/crm/gift-cards", id: "gift_cards" },
      { title: "CRM Setup", icon: Settings2, url: "/crm/setup", id: "setup" },
    ]
  },
  {
    title: "Sales Hub",
    icon: TrendingUp,
    url: "/sales",
    pattern: /^\/sales/,
    id: "sales",
    submenus: [
      { title: "Quotations", icon: Quote, url: "/sales/quotations", id: "quotations" },
      { title: "Sales Orders", icon: OrderIcon, url: "/sales/orders", id: "orders" },
      { title: "Invoice Center", icon: FileText, url: "/sales/invoices", id: "invoices" },
      { title: "Credit Notes", icon: CreditCard, url: "/sales/credit-notes", id: "credit_notes" },
      { title: "Sales Returns", icon: ArrowLeftRight, url: "/sales/returns", id: "returns" },
      { title: "Sales Reports", icon: ClipboardList, url: "/sales/reports", id: "reports" },
      { title: "Commission", icon: UserCheck, url: "/sales/commissions", id: "commissions" },
      { title: "Sales Setup", icon: Settings, url: "/sales/setup", id: "setup" },
    ]
  },
  {
    title: "Logistics Hub",
    icon: Truck,
    url: "/delivery",
    pattern: /^\/delivery/,
    id: "delivery",
    submenus: [
      { title: "Delivery Orders", icon: FileText, url: "/delivery/orders", id: "orders" },
      { title: "Dispatch Center", icon: Zap, url: "/delivery/dispatch", id: "dispatch" },
      { title: "Route Planning", icon: Route, url: "/delivery/routes", id: "routes" },
      { title: "Fleet & Drivers", icon: CarFront, url: "/delivery/fleet", id: "fleet" },
      { title: "Live Tracking", icon: Navigation, url: "/delivery/tracking", id: "tracking" },
      { title: "Confirmation", icon: CheckCircle2, url: "/delivery/confirmation", id: "confirmation" },
      { title: "Logistics Setup", icon: Settings, url: "/delivery/setup", id: "setup" },
    ]
  },
  {
    title: "Purchases",
    icon: ShoppingCart,
    url: "/purchases",
    pattern: /^\/purchases/,
    id: "purchases",
    submenus: [
      { title: "Suppliers", icon: Users2, url: "/purchases/suppliers", id: "suppliers" },
      { title: "Purchase Orders", icon: ClipboardCheck, url: "/purchases/orders", id: "orders" },
      { title: "GRN Hub", icon: PackageCheck, url: "/purchases/grn", id: "grn" },
      { title: "Vendor Invoices", icon: FileText, url: "/purchases/invoices", id: "invoices" },
      { title: "Purchase Returns", icon: ArrowLeftRight, url: "/purchases/returns", id: "returns" },
      { title: "Procurement Setup", icon: Settings, url: "/purchases/setup", id: "setup" },
      { title: "Purchases Reports", icon: ClipboardList, url: "/purchases/reports", id: "reports" },
    ]
  },
  { 
    title: "Stock Vault", 
    icon: Package, 
    url: "/inventory", 
    pattern: /^\/inventory/,
    id: "inventory",
    submenus: [
      { title: "Stock Items", icon: Box, url: "/inventory/products", id: "products" },
      { title: "Services", icon: Briefcase, url: "/inventory/services", id: "services" },
      { title: "Bundles / Combos", icon: Boxes, url: "/inventory/bundles", id: "bundles" },
      { title: "Variants", icon: Tags, url: "/inventory/variants", id: "variants" },
      { title: "Stock Levels", icon: Search, url: "/inventory/stock-levels", id: "stock_levels" },
      { title: "Warehouses", icon: Database, url: "/inventory/warehouses", id: "warehouses" },
      { title: "Stock Transfers", icon: Truck, url: "/inventory/transfers", id: "transfers" },
      { title: "Stock Adjustments", icon: Layers, url: "/inventory/adjustments", id: "adjustments" },
      { title: "Expiry Control", icon: Timer, url: "/inventory/expiry", id: "expiry" },
      { title: "Batch & Serial", icon: Barcode, url: "/inventory/batches", id: "batches" },
      { title: "Reorder Levels", icon: AlertTriangle, url: "/inventory/reorder", id: "reorder" },
      { title: "Damage & Loss", icon: Skull, url: "/inventory/damages", id: "damages" },
      { title: "Stock Valuation", icon: Scale, url: "/inventory/valuation", id: "valuation" },
      { title: "Inventory Reports", icon: ClipboardList, url: "/inventory/reports", id: "reports" },
      { title: "Inventory Setup", icon: Settings, url: "/inventory/setup", id: "setup" },
    ]
  },
  { 
    title: "Budgeting", 
    icon: Target, 
    url: "/budgeting", 
    pattern: /^\/budgeting/,
    id: "budgeting",
    submenus: [
      { title: "Budget Command", icon: LayoutDashboard, url: "/budgeting", id: "overview" },
      { title: "Budget Creation", icon: FilePlus2, url: "/budgeting/creation", id: "creation" },
      { title: "Department Budget", icon: Building, url: "/budgeting/departments", id: "departments" },
      { title: "Variance Analysis", icon: Scale, url: "/budgeting/variance", id: "variance" },
      { title: "Forecasting", icon: LineChart, url: "/budgeting/forecasting", id: "forecasting" },
      { title: "Budget Setup", icon: Settings, url: "/budgeting/setup", id: "setup" },
    ]
  },
  { 
    title: "Financial Suite", 
    icon: Calculator, 
    url: "/accounting", 
    pattern: /^\/accounting/,
    id: "accounting",
    submenus: [
      { title: "General Ledger", icon: BookOpen, url: "/accounting", id: "ledger" },
      { title: "Chart of Accounts", icon: Layers, url: "/accounting/coa", id: "coa" },
      { title: "Journal Entries", icon: History, url: "/accounting/journal", id: "journal" },
      { title: "Accounts Receivable", icon: Receipt, url: "/accounting/ar", id: "ar" },
      { title: "Accounts Payable", icon: Gavel, url: "/accounting/ap", id: "ap" },
      { title: "Cash & Bank", icon: Landmark, url: "/accounting/banking", id: "bank" },
      { title: "Fixed Assets", icon: Building, url: "/accounting/assets", id: "assets" },
      { title: "Expense Tracking", icon: ArrowRightLeft, url: "/accounting/expenses", id: "expenses" },
      { title: "Budgets", icon: PieChart, url: "/accounting/budgets", id: "budgets" },
      { title: "Tax Returns", icon: FileText, url: "/accounting/tax", id: "tax_returns" },
      { title: "Financial Setup", icon: Settings, url: "/accounting/setup", id: "setup" },
      { title: "Financial Reports", icon: ClipboardCheck, url: "/accounting/reports", id: "reports" },
    ]
  },
  { 
    title: "Administration", 
    icon: Settings, 
    url: "/admin/institution-profile", 
    pattern: /^\/admin/,
    id: "admin",
    submenus: [
      { title: "Entity Profile", icon: Building2, url: "/admin/institution-profile", id: "entity_profile" },
      { title: "System Console", icon: Monitor, url: "/admin/settings", id: "settings" },
      { title: "Institutions", icon: Store, url: "/admin/institutions", id: "institutions" },
      { title: "Branches", icon: MapPin, url: "/admin/branches", id: "branches" },
      { title: "Departments", icon: Briefcase, url: "/admin/departments", id: "departments" },
      { title: "Geo Hierarchy", icon: Globe, url: "/admin/geo-hierarchy", id: "geo_hierarchy" },
      { title: "Roles & Permissions", icon: Shield, url: "/admin/roles", id: "roles" },
      { title: "Session Manager", icon: Clock, url: "/admin/sessions", id: "sessions" },
      { title: "Data Encryption", icon: Lock, url: "/admin/encryption", id: "encryption" },
      { title: "Two-Factor Auth", icon: ShieldCheck, url: "/admin/2fa", id: "2fa" },
      { title: "IP Restriction", icon: Globe2, url: "/admin/ip-restrictions", id: "ip_restriction" },
      { title: "Approval Workflows", icon: GitPullRequest, url: "/admin/approval-workflows", id: "workflows" },
      { title: "Tax Config", icon: Percent, url: "/admin/tax", id: "tax_config" },
      { title: "Currencies", icon: Coins, url: "/admin/currencies", id: "currencies" },
      { title: "Fiscal Periods", icon: CalendarDays, url: "/admin/fiscal-periods", id: "fiscal" },
      { title: "Doc Numbering", icon: Hash, url: "/admin/document-numbering", id: "numbering" },
      { title: "Audit Logs", icon: FileClock, url: "/admin/audit-logs", id: "audit" },
      { title: "Notification Templates", icon: BellRing, url: "/admin/notifications", id: "notifications" },
      { title: "System Health", icon: Activity, url: "/admin/system-health", id: "health" },
      { title: "API Management", icon: Key, url: "/admin/api-management", id: "api" },
    ]
  },
]
